# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 6342
  start_block: 0
  contracts:
  - name: OrderbookFactory
    address:
    - 0x80a2c002268906FEC40E6731cf33C9A9EF3e97D6
    handler: src/orderbookFactory.ts
    events:
    - event: OrderbookCreated(address indexed loanToken, address indexed collateralToken, address orderbook)
  - name: PoolFactory
    address:
    - 0x6fd34F78A0021F9b75ecBa672Bfd0b3475B29d5a
    handler: src/poolFactory.ts
    events:
    - event: PoolCreated(address indexed pool, address indexed loanToken, address indexed collateralToken)
  - name: VaultFactory
    address:
    - 0x595c417199933898d6e83968F96F5FA5faa36C1f
    handler: src/vaultFactory.ts
    events:
    - event: VaultCreated(address indexed vault, address indexed token, address indexed poolManager)
  - name: OrderBook
    handler: src/orderbook.ts
    events:
    - event: BorrowOrderCanceled(address indexed borrower, uint256 rate, uint256 ltv, uint256 amount)
      field_selection:
        transaction_fields:
          - hash
    - event: BorrowOrderPlaced(address indexed borrower, uint256 rate, uint256 ltv, uint256 amount, uint256 minAmountExpected)
      field_selection:
        transaction_fields:
          - hash
    - event: OrderCanceled(bool indexed isLender, address indexed maker, uint256 rate, uint256 ltv, uint256 amount)
      field_selection:
        transaction_fields:
          - hash
    - event: OrderInserted(bool indexed isLender, address indexed maker, uint256 rate, uint256 ltv, uint256 amount)
      field_selection:
        transaction_fields:
          - hash
    - event: OrderMatched(address indexed lender, address indexed borrower, uint256 rate, uint256 ltv, uint256 amount)
      field_selection:
        transaction_fields:
          - hash
    - event: OwnershipTransferStarted(address indexed previousOwner, address indexed newOwner)
      field_selection:
        transaction_fields:
          - hash
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      field_selection:
        transaction_fields:
          - hash
    - event: Paused(address account)
      field_selection:
        transaction_fields:
          - hash
    - event: PoolWhitelisted(address indexed pool)
    - event: Unpaused(address account)
      field_selection:
        transaction_fields:
          - hash
  - name: Pool
    handler: src/pool.ts
    events:
    - event: AccrueInterest(address indexed poolAddress, uint256 prevBorrowRate, uint256 interest, uint256 feeShares)
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
    - event: Borrow(address indexed poolAddress, address caller, address indexed onBehalf, address indexed receiver, uint256 assets, uint256 shares)
    - event: Deposit(address indexed sender, address indexed owner, uint256 assets, uint256 shares)
    - event: DepositCollateral(address indexed poolAddress, address indexed caller, address indexed onBehalf, uint256 assets)
    - event: FlashLoan(address indexed caller, address indexed token, uint256 assets)
    - event: Liquidate(address indexed poolAddress, address indexed caller, address indexed borrower, uint256 repaidAssets, uint256 repaidShares, uint256 seizedAssets, uint256 badDebtAssets, uint256 badDebtShares)
    - event: Repay(address indexed poolAddress, address indexed caller, address indexed onBehalf, uint256 assets, uint256 shares)
    - event: Transfer(address indexed from, address indexed to, uint256 value)
    - event: Withdraw(address indexed sender, address indexed receiver, address indexed owner, uint256 assets, uint256 shares)
    - event: WithdrawCollateral(address indexed poolAddress, address caller, address indexed onBehalf, address indexed receiver, uint256 assets)
  - name: Vault
    handler: src/vault.ts
    events:
    - event: Deposit(address indexed sender, address indexed owner, uint256 assets, uint256 shares)
    - event: Transfer(address indexed from, address indexed to, uint256 value)
    - event: Withdraw(address indexed sender, address indexed receiver, address indexed owner, uint256 assets, uint256 shares)
unordered_multichain_mode: true
